knife4j:
  enable: true
  # 生产环境屏蔽
  # production: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    username: admin
    password: admin
  setting:
    enableFooter: false
    enableSwaggerModels: true
